services:
  - type: web
    name: lms-backend
    env: node
    plan: free
    buildCommand: 'cd backend && npm ci'
    startCommand: 'cd backend && npm start'
    envVars:
      - key: MONGO_URI
        value: $MONGO_URI
      - key: JWT_SECRET
        value: $JWT_SECRET
